### ISSUE TITLE
Build command failing due to missing 'protoc'

### ISSUE THREAD

**Issue by atrefonas** [voxelize/voxelize#7]
`yarn run dev`

```
...
 Compiling tiff v0.6.1
   Compiling prost-build v0.11.1
   Compiling image v0.23.14
   Compiling voxelize v0.8.16 (/Users/a3voices/experiments/voxelize)
   Compiling serde_urlencoded v0.7.1
   Compiling splines v4.1.1
error: failed to run custom build command for `voxelize v0.8.16 (/Users/a3voices/experiments/voxelize)`

Caused by:
  process didn't exit successfully: `/Users/a3voices/experiments/voxelize/target/release/build/voxelize-31e9bf6d5fa972cb/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '
  Could not find `protoc` installation and this build crate cannot proceed without
  this knowledge. If `protoc` is installed and this crate had trouble finding
  it, you can set the `PROTOC` environment variable with the specific path to your
  installed `protoc` binary.

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /Users/a3voices/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.11.1/src/lib.rs:1227:10
  stack backtrace:
     0:        0x1028f4d54 - std::backtrace_rs::backtrace::libunwind::trace::ha03082fdb36b8e44
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x1028f4d54 - std::backtrace_rs::backtrace::trace_unsynchronized::hf1acb3d3fce46837
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x1028f4d54 - std::sys_common::backtrace::_print_fmt::hbc7deaf5374edfd8
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
     3:        0x1028f4d54 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha9a1a8bf7485458d
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22

```

**Comment by atrefonas** [comment]
Also thanks, the other fix worked for `yarn --cwd transport run proto`

**Comment by shaoruu** [comment]
I think we updated protobuf and it now requires `protoc` to be installed on the machine. This is the docs: https://grpc.io/docs/protoc-installation/

I'll add this to the README for clarification!

**Comment by atrefonas** [comment]
Thanks, that fixed it!
